// Acción lista tabla altas
export const LISTA_BAJAS_REQUEST = 'LISTA_BAJAS_REQUEST';
export const LISTA_BAJAS_SUCCESS = 'LISTA_BAJAS_SUCCESS';
export const LISTA_BAJAS_FAIL = 'LISTA_BAJAS_FAIL';
// Acción registrar altas
export const REGISTRAR_BAJAS_REQUEST = 'REGISTRAR_BAJAS_REQUEST';
export const REGISTRAR_BAJAS_SUCCESS = 'REGISTRAR_BAJAS_SUCCESS';
export const REGISTRAR_BAJAS_FAIL = 'REGISTRAR_BAJAS_FAIL';

