// Acción lista tabla altas
export const LISTA_BAJAS_REQUEST = 'LISTA_BAJAS_REQUEST';
export const LISTA_BAJAS_SUCCESS = 'LISTA_BAJAS_SUCCESS';
export const LISTA_BAJAS_FAIL = 'LISTA_BAJAS_FAIL';
// Acción obtener bajas desde fecha inicio y termino
export const OBTENER_BAJAS_REQUEST = 'OBTENER_BAJAS_REQUEST';
export const OBTENER_BAJAS_SUCCESS = 'OBTENER_BAJAS_SUCCESS';
export const OBTENER_BAJAS_FAIL = 'OBTENER_BAJAS_FAIL';
// Acción registrar altas
export const REGISTRAR_BAJAS_REQUEST = 'REGISTRAR_BAJAS_REQUEST';
export const REGISTRAR_BAJAS_SUCCESS = 'REGISTRAR_BAJAS_SUCCESS';
export const REGISTRAR_BAJAS_FAIL = 'REGISTRAR_BAJAS_FAIL';
// Acción excluir Bajas
export const EXCLUIR_BODEGA_REQUEST = 'EXCLUIR_BODEGA_REQUEST';
export const EXCLUIR_BODEGA_SUCCESS = 'EXCLUIR_BODEGA_SUCCESS';
export const EXCLUIR_BODEGA_FAIL = 'EXCLUIR_BODEGA_FAIL';

