// Acción de carga obtener traspasos servicio 
export const TRASPASOS_SERVICIO_SUCCESS = 'TRASPASOS_SERVICIO_SUCCESS';
export const TRASPASOS_SERVICIO_FAIL = 'TRASPASOS_SERVICIO_FAIL';
export const TRASPASOS_SERVICIO_REQUEST = 'TRASPASOS_SERVICIO_REQUEST';

// Acción de carga obtener establecimiento
export const ESTABLECIMIENTO_SUCCESS = 'ESTABLECIMIENTO_SUCCESS';
export const ESTABLECIMIENTO_FAIL = 'ESTABLECIMIENTO_FAIL';
export const ESTABLECIMIENTO_REQUEST = 'ESTABLECIMIENTO_REQUEST';

// Acción de carga obtener especie
export const TRASPASOS_ESPECIE_SUCCESS = 'TRASLADO_ESPECIE_SUCCESS';
export const TRASPASOS_ESPECIE_FAIL = 'TRASLADO_ESPECIE_FAIL';
export const TRASPASOS_ESPECIE_REQUEST = 'TRASLADO_ESPECIE_REQUEST';

// Acción de carga obtener dependencia origen
export const COMBO_DEPENDENCIA_ORIGEN_REQUEST = 'COMBO_DEPENDENCIA_ORIGEN_REQUEST';
export const COMBO_DEPENDENCIA_ORIGEN_SUCCESS = 'COMBO_DEPENDENCIA_ORIGEN_SUCCESS';
export const COMBO_DEPENDENCIA_ORIGEN_FAIL = 'COMBO_DEPENDENCIA_ORIGEN_FAIL';

// Acción de carga obtener dependencia destino
export const COMBO_DEPENDENCIA_DESTINO_REQUEST = 'COMBO_DEPENDENCIA_DESTINO_REQUEST';
export const COMBO_DEPENDENCIA_DESTINO_SUCCESS = 'COMBO_DEPENDENCIA_DESTINO_SUCCESS';
export const COMBO_DEPENDENCIA_DESTINO_FAIL = 'COMBO_DEPENDENCIA_DESTINO_FAIL';

// Acción de carga Listado de traslados 
export const LISTA_TRASPASOS_REQUEST = 'LISTA_TRASPASOS_REQUEST';
export const LISTA_TRASPASOS_SUCCESS = 'LISTA_TRASPASOS_SUCCESS';
export const LISTA_TRASPASOS = 'LISTA_TRASPASOS_FAIL';

// Acción de registra formulario traslados 
export const POST_FORMULARIO_TRASPASOS_REQUEST = 'POST_FORMULARIO_TRASPASOS_REQUEST';
export const POST_FORMULARIO_TRASPASOS_SUCCESS = 'POST_FORMULARIO_TRASPASOS_SUCCESS';
export const POST_FORMULARIO_TRASPASOS_FAIL = 'POST_FORMULARIO_TRASPASOS_FAIL';

// Acción de obtiene formulario inventario traslados 
export const OBTIENE_INV_TRASPASOS_REQUEST = 'OBTIENE_INV_TRASPASOS_REQUEST';
export const OBTIENE_INV_TRASPASOS_SUCCESS = 'OBTIENE_INV_TRASPASOS_SUCCESS';
export const OBTIENE_INV_TRASPASOS_FAIL = 'OBTIENE_INV_TRASPASOS_FAIL';
