//-------------------REGISTRAR INVENTARIO--------------------------//
//------------(PASO 1)--------------//
// Acción de carga obtener todos los datos del paso 1
export const RECEPCION_SUCCESS = 'RECEPCION_SUCCESS';
export const RECEPCION_FAIL = 'RECEPCION_FAIL';
export const RECEPCION_REQUEST = 'RECEPCION_REQUEST';

// Acción de carga lista inventario registrado
export const LISTA_INVENTARIO_REGISTRADO_SUCCESS = 'LISTA_INVENTARIO_REGISTRADO_SUCCESS';
export const LISTA_INVENTARIO_REGISTRADO_FAIL = 'LISTA_INVENTARIO_REGISTRADO_FAIL';
export const LISTA_INVENTARIO_REGISTRADO_REQUEST = 'LISTA_INVENTARIO_REGISTRADO_REQUEST';

// Acción de carga combo origen presupuesto
export const ORIGEN_SUCCESS = 'ORIGEN_SUCCESS';
export const ORIGEN_FAIL = 'ORIGEN_FAIL';
export const ORIGEN_REQUEST = 'ORIGEN_REQUEST';

// Acción de carga combo COMBO_PROVEEDORES 
export const COMBO_PROVEEDORES_SUCCESS = 'COMBO_PROVEEDORES_SUCCESS';
export const COMBO_PROVEEDORES_FAIL = 'COMBO_PROVEEDORES_FAIL';
export const COMBO_PROVEEDORES_REQUEST = 'COMBO_PROVEEDORES_REQUEST';

// Acción de carga combo modalidad compra
export const MODALIDAD_COMPRA_SUCCESS = 'MODALIDAD_COMPRA_SUCCESS';
export const MODALIDAD_COMPRA_FAIL = 'MODALIDAD_COMPRA_FAIL';
export const MODALIDAD_COMPRA_REQUEST = 'MODALIDAD_COMPRA_REQUEST';

// Acción de carga servicio nombre
export const OBTENER_SERVICIO_NOMBRE_SUCCESS = 'OBTENER_SERVICIO_NOMBRE_SUCCESS';
export const OBTENER_SERVICIO_NOMBRE_FAIL = 'OBTENER_SERVICIO_NOMBRE_FAIL';
export const OBTENER_SERVICIO_NOMBRE_REQUEST = 'OBTENER_SERVICIO_NOMBRE_REQUEST';

//------------(PASO 2)--------------//
// Acción de carga combo servicio
export const SERVICIO_SUCCESS = 'SERVICIO_SUCCESS';
export const SERVICIO_FAIL = 'SERVICIO_FAIL';
export const SERVICIO_REQUEST = 'SERVICIO_REQUEST';

// Acción de carga combo dependencia
export const DEPENDENCIA_SUCCESS = 'DEPENDENCIA_SUCCESS';
export const DEPENDENCIA_FAIL = 'DEPENDENCIA_FAIL';
export const DEPENDENCIA_REQUEST = 'DEPENDENCIA_REQUEST';

// Acción de carga listado de especies
export const LISTADO_ESPECIES_BIEN_SUCCESS = 'LISTADO_ESPECIES_BIEN_SUCCESS';
export const LISTADO_ESPECIES_BIEN_FAIL = 'LISTADO_ESPECIES_BIEN_FAIL';
export const LISTADO_ESPECIES_BIEN_REQUEST = 'LISTADO_ESPECIES_BIEN_REQUEST';

// Acción de carga combo cuenta
export const CUENTA_SUCCESS = 'CUENTA_SUCCESS';
export const CUENTA_FAIL = 'CUENTA_FAIL';
export const CUENTA_REQUEST = 'CUENTA_REQUEST';

// Acción de carga combo bien
export const BIEN_REQUEST = 'BIEN_REQUEST';
export const BIEN_SUCCESS = 'BIEN_SUCCESS';
export const BIEN_FAIL = 'BIEN_FAIL';

// Acción de carga combo detalles
export const BIEN_DETALLES_SUCCESS = 'BIEN_DETALLES_SUCCESS';
export const BIEN_DETALLES_FAIL = 'BIEN_DETALLES_FAIL';
export const BIEN_DETALLES_REQUEST = 'BIEN_DETALLES_REQUEST';

//------------(PASO 3)--------------//
// export const SET_TOTAL_ACTIVO_FIJO = 'SET_TOTAL_ACTIVO_FIJO';
// Acción de post formulario inventario
export const POST_FORMULARIO_SUCCESS = 'POST_FORMULARIO_SUCCESS';
export const POST_FORMULARIO_FAIL = 'POST_FORMULARIO_FAIL';
export const POST_FORMULARIO_REQUEST = 'POST_FORMULARIO_REQUEST';

// Acción Post bienes de funcionarios
export const OBTENER_MAX_INVENTARIO_REQUEST = 'OBTENER_MAX_INVENTARIO_REQUEST';
export const OBTENER_MAX_INVENTARIO_SUCCESS = 'OBTENER_MAX_INVENTARIO_SUCCESS';
export const OBTENER_MAX_INVENTARIO_FAIL = 'OBTENER_MAX_INVENTARIO_FAIL';


//-------------------MODIFICACAR INVENTARIO--------------------------//
// Acción obtener todos los datos de formulario inventario
export const OBTENER_INVENTARIO_SUCCESS = 'OBTENER_INVENTARIO_SUCCESS';
export const OBTENER_INVENTARIO_FAIL = 'OBTENER_INVENTARIO_FAIL';
export const OBTENER_INVENTARIO_REQUEST = 'OBTENER_INVENTARIO_REQUEST';

//-------------------ANULAR INVENTARIO--------------------------//
// Acción de carga lista inventario
export const LISTA_INVENTARIO_SUCCESS = 'LISTA_INVENTARIO_SUCCESS';
export const LISTA_INVENTARIO_FAIL = 'LISTA_INVENTARIO_FAIL';
export const LISTA_INVENTARIO_REQUEST = 'LISTA_INVENTARIO_REQUEST';

// Acción anula inventario
export const ANULAR_INVENTARIO_SUCCESS = 'ANULAR_INVENTARIO_SUCCESS';
export const ANULAR_INVENTARIO_FAIL = 'ANULAR_INVENTARIO_FAIL';
export const ANULAR_INVENTARIO_REQUEST = 'ANULAR_INVENTARIO_REQUEST';


//-------------------BIENES FUNCIONARIOS--------------------------//
// Acción Post bienes de funcionarios
export const POST_FORMULARIO_BIENES_SUCCESS = 'POST_FORMULARIO_BIENES_SUCCESS';
export const POST_FORMULARIO_BIENES_FAIL = 'POST_FORMULARIO_BIENES_FAIL';
export const POST_FORMULARIO_BIENES_REQUEST = 'POST_FORMULARIO_BIENES_REQUEST';

