
/*************************** Dependencia ************************************/
// Acción registrar dependencia
export const REGISTRAR_DEPENDENCIA_REQUEST = 'REGISTRAR_DEPENDENCIA_REQUEST';
export const REGISTRAR_DEPENDENCIA_SUCCESS = 'REGISTRAR_DEPENDENCIA_SUCCESS';
export const REGISTRAR_DEPENDENCIA_FAIL = 'REGISTRAR_DEPENDENCIA_FAIL';

// Acción Lista mantenedor dependencias
export const LISTA_MANTENEDOR_DEPENDENCIA_REQUEST = 'LISTA_MANTENEDOR_DEPENDENCIA_REQUEST';
export const LISTA_MANTENEDOR_DEPENDENCIA_SUCCESS = 'LISTA_MANTENEDOR_DEPENDENCIA_SUCCESS';
export const LISTA_MANTENEDOR_DEPENDENCIA_FAIL = 'LISTA_MANTENEDOR_DEPENDENCIA_FAIL';

// Acción Trae Combo Servicios
export const COMBO_M_SERVICIO_REQUEST = 'COMBO_M_SERVICIO_REQUEST';
export const COMBO_M_SERVICIO_SUCCESS = 'COMBO_M_SERVICIO_SUCCESS';
export const COMBO_M_SERVICIO_FAIL = 'COMBO_M_SERVICIO_FAIL';

/*************************** Servicio ************************************/

// Acción Obtener Max servicio
export const OBTENER_MAX_SERVICIO_REQUEST = 'OBTENER_MAX_SERVICIO_REQUEST';
export const OBTENER_MAX_SERVICIO_SUCCESS = 'OBTENER_MAX_SERVICIO_SUCCESS';
export const OBTENER_MAX_SERVICIO_FAIL = 'OBTENER_MAX_SERVICIO_FAIL';

// Acción registrar servicios
export const REGISTRAR_SERVICIO_REQUEST = 'REGISTRAR_SERVICIO_REQUEST';
export const REGISTRAR_SERVICIO_SUCCESS = 'REGISTRAR_SERVICIO_SUCCESS';
export const REGISTRAR_SERVICIO_FAIL = 'REGISTRAR_SERVICIO_FAIL';

// Acción Lista mantenedor servicios
export const LISTA_MANTENEDOR_SERVICIO_REQUEST = 'LISTA_MANTENEDOR_SERVICIO_REQUEST';
export const LISTA_MANTENEDOR_SERVICIO_SUCCESS = 'LISTA_MANTENEDOR_SERVICIO_SUCCESS';
export const LISTA_MANTENEDOR_SERVICIO_FAIL = 'LISTA_MANTENEDOR_SERVICIO_FAIL';

// Acción Trae Combo Establecimientos
export const COMBO_M_ESTABLECIMIENTO_REQUEST = 'COMBO_M_ESTABLECIMIENTO_REQUEST';
export const COMBO_M_ESTABLECIMIENTO_SUCCESS = 'COMBO_M_ESTABLECIMIENTO_SUCCESS';
export const COMBO_M_ESTABLECIMIENTO_FAIL = 'COMBO_M_ESTABLECIMIENTO_FAIL';

/*************************** Usuario ************************************/
// Acción registrar usuarios
export const REGISTRAR_USUARIO_REQUEST = 'REGISTRAR_USUARIO_REQUEST';
export const REGISTRAR_USUARIO_SUCCESS = 'REGISTRAR_USUARIO_SUCCESS';
export const REGISTRAR_USUARIO_FAIL = 'REGISTRAR_USUARIO_FAIL';

// Acción Lista mantenedor usuarios
export const LISTA_MANTENEDOR_USUARIO_REQUEST = 'LISTA_MANTENEDOR_USUARIO_REQUEST';
export const LISTA_MANTENEDOR_USUARIO_SUCCESS = 'LISTA_MANTENEDOR_USUARIO_SUCCESS';
export const LISTA_MANTENEDOR_USUARIO_FAIL = 'LISTA_MANTENEDOR_USUARIO_FAIL';


/*************************** Especies ************************************/
// Acción Lista mantenedor especies
export const LISTA_MANTENEDOR_ESPECIE_REQUEST = 'LISTA_MANTENEDOR_ESPECIE_REQUEST';
export const LISTA_MANTENEDOR_ESPECIE_SUCCESS = 'LISTA_MANTENEDOR_ESPECIE_SUCCESS';
export const LISTA_MANTENEDOR_ESPECIE_FAIL = 'LISTA_MANTENEDOR_ESPECIE_FAIL';



