// Acción registrar dependencia
export const REGISTRAR_DEPENDENCIA_REQUEST = 'REGISTRAR_DEPENDENCIA_REQUEST';
export const REGISTRAR_DEPENDENCIA_SUCCESS = 'REGISTRAR_DEPENDENCIA_SUCCESS';
export const REGISTRAR_DEPENDENCIA_FAIL = 'REGISTRAR_DEPENDENCIA_FAIL';

// Acción Lista mantenedor dependencias
export const LISTA_MANTENEDOR_DEPENDENCIA_REQUEST = 'LISTA_MANTENEDOR_DEPENDENCIA_REQUEST';
export const LISTA_MANTENEDOR_DEPENDENCIA_SUCCESS = 'LISTA_MANTENEDOR_DEPENDENCIA_SUCCESS';
export const LISTA_MANTENEDOR_DEPENDENCIA_FAIL = 'LISTA_MANTENEDOR_DEPENDENCIA_FAIL';
