// Acción registrar dependencia
export const REGISTRAR_DEPENDENCIA_REQUEST = 'REGISTRAR_DEPENDENCIA_REQUEST';
export const REGISTRAR_DEPENDENCIA_SUCCESS = 'REGISTRAR_DEPENDENCIA_SUCCESS';
export const REGISTRAR_DEPENDENCIA_FAIL = 'REGISTRAR_DEPENDENCIA_FAIL';

// Acción Lista mantenedor dependencias
export const LISTA_MANTENEDOR_DEPENDENCIA_REQUEST = 'LISTA_MANTENEDOR_DEPENDENCIA_REQUEST';
export const LISTA_MANTENEDOR_DEPENDENCIA_SUCCESS = 'LISTA_MANTENEDOR_DEPENDENCIA_SUCCESS';
export const LISTA_MANTENEDOR_DEPENDENCIA_FAIL = 'LISTA_MANTENEDOR_DEPENDENCIA_FAIL';

// Acción registrar servicios
export const REGISTRAR_SERVICIO_REQUEST = 'REGISTRAR_SERVICIO_REQUEST';
export const REGISTRAR_SERVICIO_SUCCESS = 'REGISTRAR_SERVICIO_SUCCESS';
export const REGISTRAR_SERVICIO_FAIL = 'REGISTRAR_SERVICIO_FAIL';

// Acción Lista mantenedor servicios
export const LISTA_MANTENEDOR_SERVICIO_REQUEST = 'LISTA_MANTENEDOR_SERVICIO_REQUEST';
export const LISTA_MANTENEDOR_SERVICIO_SUCCESS = 'LISTA_MANTENEDOR_SERVICIO_SUCCESS';
export const LISTA_MANTENEDOR_SERVICIO_FAIL = 'LISTA_MANTENEDOR_SERVICIO_FAIL';

// Acción registrar usuarios
export const REGISTRAR_USUARIO_REQUEST = 'REGISTRAR_USUARIO_REQUEST';
export const REGISTRAR_USUARIO_SUCCESS = 'REGISTRAR_USUARIO_SUCCESS';
export const REGISTRAR_USUARIO_FAIL = 'REGISTRAR_USUARIO_FAIL';

// Acción Lista mantenedor usuarios
export const LISTA_MANTENEDOR_USUARIO_REQUEST = 'LISTA_MANTENEDOR_USUARIO_REQUEST';
export const LISTA_MANTENEDOR_USUARIO_SUCCESS = 'LISTA_MANTENEDOR_USUARIO_SUCCESS';
export const LISTA_MANTENEDOR_USUARIO_FAIL = 'LISTA_MANTENEDOR_USUARIO_FAIL';

// Acción registrar usuarios
export const REGISTRAR_ESPECIE_REQUEST = 'REGISTRAR_ESPECIE_REQUEST';
export const REGISTRAR_ESPECIE_SUCCESS = 'REGISTRAR_ESPECIE_SUCCESS';
export const REGISTRAR_ESPECIE_FAIL = 'REGISTRAR_ESPECIE_FAIL';

// Acción Lista mantenedor usuarios
export const LISTA_MANTENEDOR_ESPECIE_REQUEST = 'LISTA_MANTENEDOR_ESPECIE_REQUEST';
export const LISTA_MANTENEDOR_ESPECIE_SUCCESS = 'LISTA_MANTENEDOR_ESPECIE_SUCCESS';
export const LISTA_MANTENEDOR_ESPECIE_FAIL = 'LISTA_MANTENEDOR_ESPECIE_FAIL';