// Acción combo servicio informes FolioPorServicioDependencia
export const COMBO_SERVICIO_INFORME_SUCCESS = 'COMBO_SERVICIO_INFORME_SUCCESS';
export const COMBO_SERVICIO_INFORME_FAIL = 'COMBO_SERVICIO_INFORME_FAIL';
export const COMBO_SERVICIO_INFORME_REQUEST = 'COMBO_SERVICIO_INFORME_REQUEST';

// Acción combo servicio informes Cuenta Fechas
export const COMBO_CUENTA_INFORME_SUCCESS = 'COMBO_CUENTA_INFORME_SUCCESS';
export const COMBO_CUENTA_INFORME_FAIL = 'COMBO_CUENTA_INFORME_FAIL';
export const COMBO_CUENTA_INFORME_REQUEST = 'COMBO_CUENTA_INFORME_REQUEST';

