// Acción combo servicio informes FolioPorServicioDependencia
export const COMBO_SERVICIO_INFORME_SUCCESS = 'COMBO_SERVICIO_INFORME_SUCCESS';
export const COMBO_SERVICIO_INFORME_FAIL = 'COMBO_SERVICIO_INFORME_FAIL';
export const COMBO_SERVICIO_INFORME_REQUEST = 'COMBO_SERVICIO_INFORME_REQUEST';

// Acción combo servicio informes Cuenta Fechas
export const COMBO_CUENTA_INFORME_SUCCESS = 'COMBO_CUENTA_INFORME_SUCCESS';
export const COMBO_CUENTA_INFORME_FAIL = 'COMBO_CUENTA_INFORME_FAIL';
export const COMBO_CUENTA_INFORME_REQUEST = 'COMBO_CUENTA_INFORME_REQUEST';


// Acción lista servicio dependnecia informes
export const LISTA_SERVICIO_DEPENDENCIA_SUCCESS = 'LISTA_SERVICIO_DEPENDENCIA_SUCCESS';
export const LISTA_SERVICIO_DEPENDENCIA_FAIL = 'LISTA_SERVICIO_DEPENDENCIA_FAIL';
export const LISTA_SERVICIO_DEPENDENCIA_REQUEST = 'LISTA_SERVICIO_DEPENDENCIA_REQUEST';

// Acción lista cuenta fechas
export const LISTA_CUENTA_FECHAS_SUCCESS = 'LISTA_CUENTA_FECHAS_SUCCESS';
export const LISTA_CUENTA_FECHAS_FAIL = 'LISTA_CUENTA_FECHAS_FAIL';
export const LISTA_CUENTA_FECHAS_REQUEST = 'LISTA_CUENTA_FECHAS_REQUEST';
