// Acción de carga obtener  traslado servicio 
export const TRASLADO_SERVICIO_SUCCESS = 'TRASLADO_SERVICIO_SUCCESS';
export const TRASLADO_SERVICIO_FAIL = 'TRASLADO_SERVICIO_FAIL';
export const TRASLADO_SERVICIO_REQUEST = 'TRASLADO_SERVICIO_REQUEST';

// Acción de carga obtener establecimiento
export const ESTABLECIMIENTO_SUCCESS = 'ESTABLECIMIENTO_SUCCESS';
export const ESTABLECIMIENTO_FAIL = 'ESTABLECIMIENTO_FAIL';
export const ESTABLECIMIENTO_REQUEST = 'ESTABLECIMIENTO_REQUEST';

// Acción de carga obtener especie
export const TRASLADO_ESPECIE_SUCCESS = 'TRASLADO_ESPECIE_SUCCESS';
export const TRASLADO_ESPECIE_FAIL = 'TRASLADO_ESPECIE_FAIL';
export const TRASLADO_ESPECIE_REQUEST = 'TRASLADO_ESPECIE_REQUEST';