// Acción lista tabla altas
export const LISTA_INDICADORES_REQUEST = 'LISTA_INDICADORES_REQUEST';
export const LISTA_UTM_SUCCESS = 'LISTA_UTM_SUCCESS';
export const LISTA_UF_SUCCESS = 'LISTA_UF_SUCCESS';
export const LISTA_DOLAR_SUCCESS = 'LISTA_DOLAR_SUCCESS';
export const LISTA_BITCOIN_SUCCESS = 'LISTA_BITCOIN_SUCCESS';
export const LISTA_INDICADORES_FAIL = 'LISTA_INDICADORES_FAIL';
