// Acción lista tabla altas
export const OBTENER_ALTAS_REGISTRADAS_REQUEST = 'OBTENER_ALTAS_REGISTRADAS_REQUEST';
export const OBTENER_ALTAS_REGISTRADAS_SUCCESS = 'OBTENER_ALTAS_REGISTRADAS_SUCCESS';
export const OBTENER_ALTAS_REGISTRADAS_FAIL = 'OBTENER_ALTAS_REGISTRADAS_FAIL';

// Acción obtener tabla altas
export const OBTENER_ALTAS_REQUEST = 'OBTENER_ALTAS_REQUEST';
export const OBTENER_ALTAS_SUCCESS = 'OBTENER_ALTAS_SUCCESS';
export const OBTENER_ALTAS_FAIL = 'OBTENER_ALTAS_FAIL';

// Acción anular altas
export const ANULAR_ALTAS_REQUEST = 'ANULAR_ALTAS_REQUEST';
export const ANULAR_ALTAS_SUCCESS = 'ANULAR_ALTAS_SUCCESS';
export const ANULAR_ALTAS_FAIL = 'ANULAR_ALTAS_FAIL';

// Acción registrar altas
export const REGISTRAR_ALTAS_REQUEST = 'REGISTRAR_ALTAS_REQUEST';
export const REGISTRAR_ALTAS_SUCCESS = 'REGISTRAR_ALTAS_SUCCESS';
export const REGISTRAR_ALTAS_FAIL = 'REGISTRAR_ALTAS_FAIL';

// Acción obtener etiquetas altas
export const ETIQUETAS_ALTAS_REQUEST = 'ETIQUETAS_ALTAS_REQUEST';
export const ETIQUETAS_ALTAS_SUCCESS = 'ETIQUETAS_ALTAS_SUCCESS';
export const ETIQUETAS_ALTAS_FAIL = 'ETIQUETAS_ALTAS_FAIL';

// Acción obtener firmas altas
export const OBTENER_FIRMAS_ALTAS_REQUEST = 'OBTENER_FIRMAS_ALTAS_REQUEST';
export const OBTENER_FIRMAS_ALTAS_SUCCESS = 'OBTENER_FIRMAS_ALTAS_SUCCESS';
export const OBTENER_FIRMAS_ALTAS_FAIL = 'OBTENER_FIRMAS_ALTAS_FAIL';

// Acción obtener unidades
export const OBTENER_UNIDADES_REQUEST = 'OBTENER_UNIDADES_REQUEST';
export const OBTENER_UNIDADES_SUCCESS = 'OBTENER_UNIDADES_SUCCESS';
export const OBTENER_UNIDADES_FAIL = 'OBTENER_UNIDADES_FAIL';

